export { default as image1 } from '../images/galleryimages/before-disaster.jpg'
export { default as image2 } from '../images/galleryimages/emtombment.jpg'
export { default as image3 } from '../images/galleryimages/kids.jpg'
export { default as image4 } from '../images/galleryimages/person.jpg'
export { default as image5 } from '../images/galleryimages/photo.jpg'